/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PShortcodeImport } from './routes/p.$shortcode'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PShortcodeRoute = PShortcodeImport.update({
  id: '/p/$shortcode',
  path: '/p/$shortcode',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/p/$shortcode': {
      id: '/p/$shortcode'
      path: '/p/$shortcode'
      fullPath: '/p/$shortcode'
      preLoaderRoute: typeof PShortcodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$shortcode': typeof PShortcodeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$shortcode': typeof PShortcodeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/p/$shortcode': typeof PShortcodeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$shortcode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$shortcode'
  id: '__root__' | '/' | '/p/$shortcode'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PShortcodeRoute: typeof PShortcodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PShortcodeRoute: PShortcodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/p/$shortcode"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/p/$shortcode": {
      "filePath": "p.$shortcode.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
